import type { BenchmarkSession } from "@/types/benchmark";

export interface SessionPreset {
  id: string;
  title: string;
  description: string;
  badge: string;
  sessionA: BenchmarkSession;
  sessionB: BenchmarkSession;
}

/**
 * Built-in comparison presets for educational exploration.
 */
export const DEFAULT_SESSION_PRESETS: SessionPreset[] = [
  {
    id: "hardware-vs-js",
    title: "WebCrypto Hardware vs JavaScript Engine",
    description:
      "Compare hardware-accelerated WebCrypto implementations (AES-GCM, SHA-256) against pure JavaScript cipher routines.",
    badge: "Hardware Acceleration",
    sessionA: {
      id: "preset-js-engine",
      timestamp: new Date("2026-07-28T10:00:00Z"),
      inputSize: 1024,
      iterations: 100,
      deviceInfo: {
        userAgent: "Mozilla/5.0 (JS Fallback Engine)",
        hardwareConcurrency: 4,
        deviceMemory: 8,
        language: "en-US",
        platform: "Win32",
        timezone: "UTC",
        screen: { width: 1920, height: 1080, colorDepth: 24, pixelDepth: 24 },
      },
      results: [
        {
          cipherId: "aes",
          cipherName: "AES-GCM (128-bit)",
          category: "symmetric",
          inputSize: 1024,
          direction: "encrypt",
          iterations: 100,
          averageTime: 0.8542,
          minTime: 0.721,
          maxTime: 1.452,
          stdDev: 0.12,
          totalTime: 85.42,
          operationsPerSecond: 1170.68,
          timestamp: new Date("2026-07-28T10:00:00Z"),
          workerExecutionTime: 1.12,
          memoryUsage: 45056,
          implementation: "JavaScript",
          status: "success",
        },
        {
          cipherId: "sha256",
          cipherName: "SHA-256",
          category: "hash",
          inputSize: 1024,
          direction: "hash",
          iterations: 100,
          averageTime: 0.4215,
          minTime: 0.385,
          maxTime: 0.912,
          stdDev: 0.08,
          totalTime: 42.15,
          operationsPerSecond: 2372.47,
          timestamp: new Date("2026-07-28T10:00:00Z"),
          workerExecutionTime: 0.65,
          memoryUsage: 20480,
          implementation: "JavaScript",
          status: "success",
        },
        {
          cipherId: "rsa",
          cipherName: "RSA-OAEP (2048-bit)",
          category: "asymmetric",
          inputSize: 1024,
          direction: "encrypt",
          iterations: 50,
          averageTime: 14.821,
          minTime: 13.52,
          maxTime: 18.91,
          stdDev: 1.15,
          totalTime: 741.05,
          operationsPerSecond: 67.47,
          timestamp: new Date("2026-07-28T10:00:00Z"),
          workerExecutionTime: 15.45,
          memoryUsage: 184320,
          implementation: "JavaScript",
          status: "success",
        },
        {
          cipherId: "caesar",
          cipherName: "Caesar Cipher",
          category: "classical",
          inputSize: 1024,
          direction: "encrypt",
          iterations: 100,
          averageTime: 0.0912,
          minTime: 0.078,
          maxTime: 0.215,
          stdDev: 0.02,
          totalTime: 9.12,
          operationsPerSecond: 10964.91,
          timestamp: new Date("2026-07-28T10:00:00Z"),
          workerExecutionTime: 0.28,
          memoryUsage: 8192,
          implementation: "JavaScript",
          status: "success",
        },
      ],
    },
    sessionB: {
      id: "preset-webcrypto-native",
      timestamp: new Date("2026-07-28T10:05:00Z"),
      inputSize: 1024,
      iterations: 100,
      deviceInfo: {
        userAgent: "Mozilla/5.0 (WebCrypto Native AES-NI)",
        hardwareConcurrency: 8,
        deviceMemory: 16,
        language: "en-US",
        platform: "Win32",
        timezone: "UTC",
        screen: { width: 1920, height: 1080, colorDepth: 24, pixelDepth: 24 },
      },
      results: [
        {
          cipherId: "aes",
          cipherName: "AES-GCM (128-bit)",
          category: "symmetric",
          inputSize: 1024,
          direction: "encrypt",
          iterations: 100,
          averageTime: 0.1821,
          minTime: 0.152,
          maxTime: 0.312,
          stdDev: 0.03,
          totalTime: 18.21,
          operationsPerSecond: 5491.48,
          timestamp: new Date("2026-07-28T10:05:00Z"),
          workerExecutionTime: 0.32,
          memoryUsage: 12288,
          implementation: "WebCrypto",
          status: "success",
        },
        {
          cipherId: "sha256",
          cipherName: "SHA-256",
          category: "hash",
          inputSize: 1024,
          direction: "hash",
          iterations: 100,
          averageTime: 0.0984,
          minTime: 0.082,
          maxTime: 0.198,
          stdDev: 0.015,
          totalTime: 9.84,
          operationsPerSecond: 10162.6,
          timestamp: new Date("2026-07-28T10:05:00Z"),
          workerExecutionTime: 0.21,
          memoryUsage: 6144,
          implementation: "WebCrypto",
          status: "success",
        },
        {
          cipherId: "rsa",
          cipherName: "RSA-OAEP (2048-bit)",
          category: "asymmetric",
          inputSize: 1024,
          direction: "encrypt",
          iterations: 50,
          averageTime: 3.912,
          minTime: 3.42,
          maxTime: 5.12,
          stdDev: 0.34,
          totalTime: 195.6,
          operationsPerSecond: 255.62,
          timestamp: new Date("2026-07-28T10:05:00Z"),
          workerExecutionTime: 4.25,
          memoryUsage: 49152,
          implementation: "WebCrypto",
          status: "success",
        },
        {
          cipherId: "caesar",
          cipherName: "Caesar Cipher",
          category: "classical",
          inputSize: 1024,
          direction: "encrypt",
          iterations: 100,
          averageTime: 0.0885,
          minTime: 0.075,
          maxTime: 0.198,
          stdDev: 0.018,
          totalTime: 8.85,
          operationsPerSecond: 11299.43,
          timestamp: new Date("2026-07-28T10:05:00Z"),
          workerExecutionTime: 0.25,
          memoryUsage: 7168,
          implementation: "JavaScript",
          status: "success",
        },
      ],
    },
  },
  {
    id: "input-scaling",
    title: "1 KB vs 64 KB Input Payload Scaling",
    description:
      "Observe how cipher execution time grows as message payload size increases 64-fold.",
    badge: "Payload Scaling O(N)",
    sessionA: {
      id: "preset-1kb-payload",
      timestamp: new Date("2026-07-28T11:00:00Z"),
      inputSize: 1024,
      iterations: 100,
      deviceInfo: {
        userAgent: "Mozilla/5.0 (Standard CPU)",
        hardwareConcurrency: 8,
        language: "en-US",
        platform: "Win32",
        timezone: "UTC",
        screen: { width: 1920, height: 1080, colorDepth: 24, pixelDepth: 24 },
      },
      results: [
        {
          cipherId: "aes",
          cipherName: "AES-GCM (128-bit)",
          category: "symmetric",
          inputSize: 1024,
          direction: "encrypt",
          iterations: 100,
          averageTime: 0.215,
          minTime: 0.18,
          maxTime: 0.38,
          stdDev: 0.04,
          totalTime: 21.5,
          operationsPerSecond: 4651.16,
          timestamp: new Date("2026-07-28T11:00:00Z"),
          workerExecutionTime: 0.35,
          memoryUsage: 14336,
          status: "success",
        },
        {
          cipherId: "sha256",
          cipherName: "SHA-256",
          category: "hash",
          inputSize: 1024,
          direction: "hash",
          iterations: 100,
          averageTime: 0.112,
          minTime: 0.09,
          maxTime: 0.22,
          stdDev: 0.02,
          totalTime: 11.2,
          operationsPerSecond: 8928.57,
          timestamp: new Date("2026-07-28T11:00:00Z"),
          workerExecutionTime: 0.23,
          memoryUsage: 8192,
          status: "success",
        },
      ],
    },
    sessionB: {
      id: "preset-64kb-payload",
      timestamp: new Date("2026-07-28T11:05:00Z"),
      inputSize: 65536,
      iterations: 100,
      deviceInfo: {
        userAgent: "Mozilla/5.0 (Standard CPU)",
        hardwareConcurrency: 8,
        language: "en-US",
        platform: "Win32",
        timezone: "UTC",
        screen: { width: 1920, height: 1080, colorDepth: 24, pixelDepth: 24 },
      },
      results: [
        {
          cipherId: "aes",
          cipherName: "AES-GCM (128-bit)",
          category: "symmetric",
          inputSize: 65536,
          direction: "encrypt",
          iterations: 100,
          averageTime: 2.915,
          minTime: 2.45,
          maxTime: 4.82,
          stdDev: 0.32,
          totalTime: 291.5,
          operationsPerSecond: 343.05,
          timestamp: new Date("2026-07-28T11:05:00Z"),
          workerExecutionTime: 3.45,
          memoryUsage: 262144,
          status: "success",
        },
        {
          cipherId: "sha256",
          cipherName: "SHA-256",
          category: "hash",
          inputSize: 65536,
          direction: "hash",
          iterations: 100,
          averageTime: 1.542,
          minTime: 1.28,
          maxTime: 2.85,
          stdDev: 0.21,
          totalTime: 154.2,
          operationsPerSecond: 648.5,
          timestamp: new Date("2026-07-28T11:05:00Z"),
          workerExecutionTime: 1.89,
          memoryUsage: 147456,
          status: "success",
        },
      ],
    },
  },
  {
    id: "thread-concurrency",
    title: "2-Core Low-Power vs 16-Core Multi-Thread Worker",
    description:
      "Analyze Web Worker thread pool throughput gains and message queue latency under different hardware concurrency conditions.",
    badge: "Thread Concurrency",
    sessionA: {
      id: "preset-2core-cpu",
      timestamp: new Date("2026-07-28T12:00:00Z"),
      inputSize: 4096,
      iterations: 200,
      deviceInfo: {
        userAgent: "Mozilla/5.0 (Dual-Core Mobile)",
        hardwareConcurrency: 2,
        deviceMemory: 4,
        language: "en-US",
        platform: "Linux armv8l",
        timezone: "UTC",
        screen: { width: 390, height: 844, colorDepth: 24, pixelDepth: 3 },
      },
      results: [
        {
          cipherId: "aes",
          cipherName: "AES-GCM",
          category: "symmetric",
          inputSize: 4096,
          direction: "encrypt",
          iterations: 200,
          averageTime: 1.254,
          minTime: 0.98,
          maxTime: 2.85,
          stdDev: 0.28,
          totalTime: 250.8,
          operationsPerSecond: 797.45,
          timestamp: new Date("2026-07-28T12:00:00Z"),
          workerExecutionTime: 2.45,
          memoryUsage: 81920,
          status: "success",
        },
        {
          cipherId: "bcrypt",
          cipherName: "Bcrypt (KDF)",
          category: "kdf",
          inputSize: 64,
          direction: "hash",
          iterations: 10,
          averageTime: 85.42,
          minTime: 79.2,
          maxTime: 105.4,
          stdDev: 6.2,
          totalTime: 854.2,
          operationsPerSecond: 11.71,
          timestamp: new Date("2026-07-28T12:00:00Z"),
          workerExecutionTime: 87.12,
          memoryUsage: 524288,
          status: "success",
        },
      ],
    },
    sessionB: {
      id: "preset-16core-cpu",
      timestamp: new Date("2026-07-28T12:05:00Z"),
      inputSize: 4096,
      iterations: 200,
      deviceInfo: {
        userAgent: "Mozilla/5.0 (16-Core Workstation)",
        hardwareConcurrency: 16,
        deviceMemory: 32,
        language: "en-US",
        platform: "Win32",
        timezone: "UTC",
        screen: { width: 2560, height: 1440, colorDepth: 24, pixelDepth: 1 },
      },
      results: [
        {
          cipherId: "aes",
          cipherName: "AES-GCM",
          category: "symmetric",
          inputSize: 4096,
          direction: "encrypt",
          iterations: 200,
          averageTime: 0.312,
          minTime: 0.25,
          maxTime: 0.62,
          stdDev: 0.05,
          totalTime: 62.4,
          operationsPerSecond: 3205.13,
          timestamp: new Date("2026-07-28T12:05:00Z"),
          workerExecutionTime: 0.52,
          memoryUsage: 28672,
          status: "success",
        },
        {
          cipherId: "bcrypt",
          cipherName: "Bcrypt (KDF)",
          category: "kdf",
          inputSize: 64,
          direction: "hash",
          iterations: 10,
          averageTime: 22.15,
          minTime: 20.1,
          maxTime: 28.5,
          stdDev: 1.8,
          totalTime: 221.5,
          operationsPerSecond: 45.15,
          timestamp: new Date("2026-07-28T12:05:00Z"),
          workerExecutionTime: 22.95,
          memoryUsage: 262144,
          status: "success",
        },
      ],
    },
  },
];
