export type CipherOptionValue = string | number | boolean

export interface CipherDefinition {
  id: string;
  name: string;
  category: "classical" | "symmetric" | "hash" | "asymmetric";
  description: string;
  defaultKey: string;
  defaultInput: string;
  securityStatus: "recommended" | "secure" | "legacy" | "deprecated" | "broken" | "experimental";
  keyPlaceholder?: string;
  keySize?: string;
  practicalUseCases?: string[];
  /** Cipher IDs the learner should be comfortable with before tackling this one */
  prerequisites?: string[];
  /** Cipher IDs that make natural next steps after exploring this one */
  recommendedNext?: string[];
  options?: {
    name: string;
    id: string;
    type: "number" | "text" | "boolean" | "select";
    default: CipherOptionValue;
    choices?: { label: string; value: CipherOptionValue }[];
  }[];
}

export const CIPHER_REGISTRY: CipherDefinition[] = [
  {
    id: "caesar",
    name: "Caesar Cipher",
    category: "classical",
    description:
      "A simple shift substitution cipher where each letter in the plaintext is shifted by a fixed number of positions.",
    defaultKey: "3",
    defaultInput: "Hello, World!",
    securityStatus: "broken",
    keyPlaceholder: "Shift (e.g. 3)",
    recommendedNext: ["rot13", "vigenere", "railfence"],
  },
  {
    id: "rot13",
    name: "ROT13",
    category: "classical",
    description:
      "A special case of Caesar cipher with a fixed shift value of 13.",
    defaultKey: "",
    defaultInput: "Hello, World!",
    securityStatus: "broken",
    prerequisites: ["caesar"],
    recommendedNext: ["vigenere", "atbash"],
  },
  {
    id: "vigenere",
    name: "Vigenère Cipher",
    category: "classical",
    description:
      "A polyalphabetic substitution cipher that uses a keyword to shift characters in repeating cycles.",
    defaultKey: "LEMON",
    defaultInput: "ATTACKATDAWN",
    securityStatus: "broken",
    keyPlaceholder: "Keyword (e.g. LEMON)",
    prerequisites: ["caesar"],
    recommendedNext: ["playfair", "railfence", "xor"],
  },
  {
    id: "atbash",
    name: "Atbash Cipher",
    category: "classical",
    description:
      "A monoalphabetic substitution cipher formed by reversing the alphabet (A becomes Z, B becomes Y, etc.).",
    defaultKey: "",
    defaultInput: "Hello, World!",
    securityStatus: "broken",
    prerequisites: ["caesar"],
    recommendedNext: ["playfair", "vigenere"],
  },
  {
    id: "playfair",
    name: "Playfair Cipher",
    category: "classical",
    description:
      "A polygraphic substitution cipher that encrypts pairs of letters using a dynamic 5x5 key matrix.",
    defaultKey: "PLAYFAIR EXAMPLE",
    defaultInput: "HIDE THE GOLD IN THE TREE STUMP",
    securityStatus: "broken",
    keyPlaceholder: "Key phrase",
    prerequisites: ["vigenere"],
    recommendedNext: ["des", "xor"],
  },
  {
    id: "railfence",
    name: "Rail Fence Cipher",
    category: "classical",
    description:
      'A transposition cipher where plaintext is written diagonally down and up on successive "rails" of a fence.',
    defaultKey: "3",
    defaultInput: "WE ARE DISCOVERED FLEE AT ONCE",
    securityStatus: "broken",
    keyPlaceholder: "Number of rails (e.g. 3)",
    prerequisites: ["caesar"],
    recommendedNext: ["vigenere", "des"],
  },
  {
    id: "xor",
    name: "XOR Cipher",
    category: "symmetric",
    description:
      "A simple stream cipher performing byte-wise XOR operations between plaintext and key.",
    defaultKey: "secret",
    defaultInput: "Hello, World!",
    securityStatus: "deprecated",
    keyPlaceholder: "Secret key string",
    prerequisites: ["vigenere"],
    recommendedNext: ["des", "aes", "otp"],
  },
  {
    id: "otp",
    name: "One-Time Pad (OTP)",
    category: "symmetric",
    description:
      "An unbreakable cipher when used with a truly random, single-use key of equal length to the plaintext.",
    defaultKey: "supersecretkeystring",
    defaultInput: "Hello, World!",
    securityStatus: "secure",
    keyPlaceholder: "Key (must match or exceed input length)",
  },
  {
    id: "des",
    name: "DES",
    category: "symmetric",
    description:
      "Data Encryption Standard. A legacy 64-bit block cipher utilizing a 56-bit key size.",
    defaultKey: "133457799BBCDDF1",
    defaultInput: "0123456789ABCDEF",
    securityStatus: "broken",
    keyPlaceholder: "16-character hex key",
    keySize: "56 bits",
    practicalUseCases: ["Legacy systems interoperability", "Educational purposes (understanding classical block ciphers)"],
    prerequisites: ["xor"],
    recommendedNext: ["3des", "aes"],
    options: [
      {
        name: "Hex Input Mode",
        id: "hexInput",
        type: "boolean",
        default: true,
      },
    ],
  },
  {
    id: "3des",
    name: "3DES (Triple DES)",
    category: "symmetric",
    description:
      "Applies the DES algorithm three times to each data block with two or three keys to increase security.",
    defaultKey: "0123456789ABCDEF0123456789ABCDEF",
    defaultInput: "Hello, World!",
    securityStatus: "deprecated",
    keyPlaceholder: "32-character hex key (2-Key) or 48-character (3-Key)",
    prerequisites: ["des"],
    recommendedNext: ["aes", "camellia"],
    options: [
      {
        name: "Hex Input Mode",
        id: "hexInput",
        type: "boolean",
        default: false,
      },
    ],
  },
  {
    id: 'aes-xts',
    name: 'AES-XTS',
    category: 'symmetric',
    description: 'A tweakable mode (IEEE P1619) for disk-sector encryption, composed from the existing AES module — the sector number IS the tweak, so no IV needs to be stored per sector. Confidentiality-only, no authentication tag (unlike AES-GCM).',
    defaultKey: '2b7e151628aed2a6abf7158809cf4f3c|000102030405060708090a0b0c0d0e0f',
    defaultInput: `0|${'0'.repeat(32)}`,
    securityStatus: 'secure',
    keyPlaceholder: 'dataKeyHex|tweakKeyHex (must be different keys)',
  },
  {
    id: "aes",
    name: "AES",
    category: "symmetric",
    description:
      "Advanced Encryption Standard. A highly secure, standard block cipher supporting key sizes of 128, 192, or 256 bits.",
    defaultKey: "000102030405060708090a0b0c0d0e0f",
    defaultInput: "00112233445566778899aabbccddeeff",
    securityStatus: "recommended",
    keyPlaceholder: "32/48/64-character hex key",
    keySize: "128, 192, or 256 bits",
    practicalUseCases: ["Secure web traffic (HTTPS)", "File encryption", "VPNs", "Disk encryption"],
    prerequisites: ["des"],
    recommendedNext: ["chacha20-poly1305", "sha256", "hmac"],
    options: [
      {
        name: "Mode of Operation",
        id: "mode",
        type: "select",
        default: "ECB",
        choices: [
          { label: "ECB (Electronic Codebook)", value: "ECB" },
          { label: "CBC (Cipher Block Chaining)", value: "CBC" },
          { label: "CTR (Counter)", value: "CTR" },
          { label: "CFB (Cipher Feedback)", value: "CFB" },
          { label: "OFB (Output Feedback)", value: "OFB" },
        ],
      },
      {
        name: "Hex Input Mode",
        id: "hexInput",
        type: "boolean",
        default: true,
      },
    ],
  },
  {
    id: "camellia",
    name: "Camellia",
    category: "symmetric",
    description:
      "A symmetric key block cipher jointly developed by Mitsubishi Electric and NTT, widely used and standardized (RFC 3713).",
    defaultKey: "0123456789abcdeffedcba9876543210",
    defaultInput: "0123456789abcdeffedcba9876543210",
    securityStatus: "secure",
    keyPlaceholder: "32/48/64-character hex key (128/192/256-bit)",
    options: [
      {
        name: "Mode of Operation",
        id: "mode",
        type: "select",
        default: "ECB",
        choices: [
          { label: "ECB (Electronic Codebook)", value: "ECB" },
          { label: "CBC (Cipher Block Chaining)", value: "CBC" },
        ],
      },
      {
        name: "Padding",
        id: "padding",
        type: "boolean",
        default: true,
      },
      {
        name: "Hex Input Mode",
        id: "hexInput",
        type: "boolean",
        default: true,
      },
    ],
  },
  {
    id: 'serpent',
    name: 'Serpent',
    category: 'symmetric',
    description: 'An AES finalist (1998, runner-up to Rijndael) with the largest security margin of the finalists — 32 rounds using 8 different S-boxes cycled per round, versus AES\'s single S-box.',
    defaultKey: '000102030405060708090a0b0c0d0e0f',
    defaultInput: '00112233445566778899aabbccddeeff',
    securityStatus: 'secure',
    keyPlaceholder: '32-character hex key (128-bit)',
  },
  {
    id: 'chacha20-poly1305',
    name: 'ChaCha20-Poly1305',
    category: 'symmetric',
    description: 'RFC 8439 AEAD combining the existing ChaCha20 and Poly1305 modules — the software-oriented alternative to AES-GCM, used by TLS 1.3 and WireGuard when hardware AES acceleration isn\'t available.',
    defaultKey: '808182838485868788898a8b8c8d8e8f909192939495969798999a9b9c9d9e|070000004041424344454647',
    defaultInput: '4c6164696573',
    securityStatus: 'recommended',
    keyPlaceholder: 'keyHex(32B)|nonceHex(12B)|aadHex(optional)',
    prerequisites: ["aes"],
    recommendedNext: ["xchacha20", "ascon", "hmac"],
  },
  {
    id: 'speck',
    name: 'Speck128/128',
    category: 'symmetric',
    description: 'An NSA lightweight ARX cipher (2013) using only addition, rotation, and XOR — no S-boxes or lookup tables at all, unlike every other symmetric cipher in this registry.',
    defaultKey: '0f0e0d0c0b0a09080706050403020100',
    defaultInput: '6f6e6920736968746d2073696874706d',
    securityStatus: 'secure',
    keyPlaceholder: '32-character hex key (128-bit)',
  },
  {
    id: 'aes-ccm',
    name: 'AES-CCM',
    category: 'symmetric',
    description: 'Counter with CBC-MAC (NIST SP 800-38C) — an authenticated mode composed from AES, contrasted with AES-GCM: authentication here is literal CBC-MAC re-running the block cipher, not GHASH polynomial evaluation.',
    defaultKey: '2b7e151628aed2a6abf7158809cf4f3c|000102030405060708090a0b',
    defaultInput: '48656c6c6f2c20574f524c4421',
    securityStatus: 'secure',
    keyPlaceholder: 'keyHex|nonceHex(12 bytes)|aadHex(optional)',
  },
  {
    id: 'threefish',
    name: 'Threefish-256',
    category: 'symmetric',
    description: 'A tweakable, large-block ARX cipher (2008) underlying the Skein hash function (a SHA-3 finalist). 256-bit block, 72 rounds, and a 128-bit tweak that varies ciphertext without changing the key — no other cipher here exposes a tweak input.',
    defaultKey: '17161514131211101f1e1d1c1b1a191827262524232221202f2e2d2c2b2a2928|07060504030201000f0e0d0c0b0a0908',
    defaultInput: '0'.repeat(64),
    securityStatus: 'secure',
    keyPlaceholder: '64-char hex key, optionally "|32-char hex tweak"',
  },
  {
    id: 'xchacha20',
    name: 'XChaCha20',
    category: 'symmetric',
    description: 'The 192-bit-nonce extension of ChaCha20 (used by libsodium) — an HChaCha20 subkey-derivation step, the ChaCha20 sibling of this batch\'s XSalsa20, lets you pick nonces randomly instead of managing a counter.',
    defaultKey: '808182838485868788898a8b8c8d8e8f909192939495969798999a9b9c9d9e|404142434445464748494a4b4c4d4e4f5051525354555657',
    defaultInput: '4c6164696573',
    securityStatus: 'secure',
    keyPlaceholder: 'keyHex(32B)|nonceHex(24B)',
  },
  {
    id: 'twofish',
    name: 'Twofish',
    category: 'symmetric',
    description:
      'AES finalist by Bruce Schneier et al. (1998). 128-bit block, 128/192/256-bit keys, 16-round Feistel. Uses key-dependent S-boxes (derived via RS matrix over GF(2^8)), MDS matrix diffusion, PHT, and 40 subkeys. Used in GnuPG and VeraCrypt. Never broken.',
    defaultKey: '00000000000000000000000000000000',
    defaultInput: '00000000000000000000000000000000',
    securityStatus: 'secure',
    keyPlaceholder: '128/192/256-bit key as 32/48/64 hex chars',
  },
  {
    id: 'gost',
    name: 'GOST 28147-89',
    category: 'symmetric',
    description: 'The Soviet/Russian government standard block cipher (declassified 1994) — 256-bit key, 32-round Feistel. Uniquely, the S-boxes are a negotiated parameter, not fixed by the standard; this demo uses a published reference set.',
    defaultKey: '000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f',
    defaultInput: '0000000000000000',
    securityStatus: 'secure',
    keyPlaceholder: '64-character hex key (256-bit)',
  },
  {
    id: 'rc2',
    name: 'RC2',
    category: 'symmetric',
    description:
      'Ron Rivest\'s 1987 variable-key block cipher (RFC 2268). First cipher exportable from the US under 1990s export controls via "effective key bits" parameter. Used in SSL 2/3, TLS, and S/MIME. Mix-and-mash round structure. Historical/educational only — broken at ≤40-bit effective keys.',
    defaultKey: '0000000000000000',
    defaultInput: '0000000000000000',
    securityStatus: 'broken',
    keyPlaceholder: '1–128 byte key as hex',
  },
  {
    id: 'enigma',
    name: 'Enigma (I, 3-rotor)',
    category: 'symmetric', // confirm against how other classical ciphers (playfair, vigenere, etc.) are categorized
    description: 'The historical WWII 3-rotor Wehrmacht cipher machine, with plugboard and reflector. Self-reciprocal (same settings encrypt and decrypt), and — a real historical weakness — no letter ever maps to itself.',
    defaultKey: 'I,II,III|A,A,A|1,1,1|',
    defaultInput: 'HELLOWORLD',
    securityStatus: 'broken',
    keyPlaceholder: 'rotors|positions|ringSettings|plugPairs — e.g. I,II,III|A,A,A|1,1,1|AB,CD',
  },
  {
    id: 'ascon',
    name: 'ASCON-128',
    category: 'symmetric',
    description:
      'NIST-selected lightweight cryptography standard (SP 800-232, 2023). Authenticated encryption with associated data (AEAD) — encrypts and authenticates simultaneously using a 320-bit sponge permutation. Designed for IoT and constrained devices. Output = nonce + ciphertext + 128-bit tag.',
    defaultKey: '000102030405060708090a0b0c0d0e0f',
    defaultInput: '48656c6c6f20576f726c64',
    securityStatus: 'secure',
    keyPlaceholder: '128-bit key as 32 hex chars',
  },
  {
    id: 'xsalsa20',
    name: 'XSalsa20',
    category: 'symmetric',
    description: 'The 192-bit-nonce extension of Salsa20 (used by NaCl/libsodium) — an HSalsa20 subkey-derivation step lets you pick nonces randomly instead of managing a counter.',
    defaultKey: '1b27556473e985d462cd51197a9a46c76009549eac6474f206c4ee0844f6838|69696ee955b62b73cd62bda875fc73d68219e0036b7a0b37',
    defaultInput: '4c6164696573',
    securityStatus: 'secure',
    keyPlaceholder: 'keyHex(32B)|nonceHex(24B)',
  },
  {
    id: 'trivium',
    name: 'Trivium',
    category: 'symmetric',
    description: 'eSTREAM Phase 3 stream cipher (ISO/IEC 29192-3). Three coupled 93/84/111-bit NLFSRs with 288-bit total state. 80-bit key, 80-bit IV, 1152 warm-up clocks before keystream. Most analysed stream cipher — one AND gate per output bit in hardware. Output = IV(20 hex) + ciphertext.',
    defaultKey: '00000000000000000000',
    defaultInput: '48656c6c6f20576f726c64',
    securityStatus: 'legacy',
    keyPlaceholder: '80-bit key as 20 hex chars',
  },
  {
    id: 'sm4',
    name: 'SM4',
    category: 'symmetric',
    description:
      'Chinese national standard block cipher (GB/T 32907-2016, ISO/IEC 18033-3, RFC 8998). Mandatory in Chinese internet and financial infrastructure; now part of TLS 1.3 cipher suites. 128-bit block, 128-bit key, 32-round SPN with a single S-box and linear transform.',
    defaultKey: '0123456789abcdeffedcba9876543210',
    defaultInput: '0123456789abcdeffedcba9876543210',
    securityStatus: 'secure',
    keyPlaceholder: '128-bit key as 32 hex chars',
  },
  {
    id: 'present',
    name: 'PRESENT',
    category: 'symmetric',
    description: "Ultra-lightweight block cipher (ISO/IEC 29192-2:2012). Smallest standardised cipher: PRESENT-80 fits in 1,075 gate equivalents — vs AES's ~3,400 GE. 64-bit block, 80 or 128-bit key, 31-round SPN with a 4-bit S-box and a 64-bit bit-permutation P-layer.",
    defaultKey: '00000000000000000000',
    defaultInput: '0000000000000000',
    securityStatus: 'legacy',
    keyPlaceholder: '80-bit key (20 hex) or 128-bit key (32 hex)',
  },
  {
    id: 'simon32',
    name: 'SIMON-32/64',
    category: 'symmetric',
    description: 'NSA lightweight block cipher targeting 8/16-bit microcontrollers. Uses 16-bit words, a 32-bit block, and a 64-bit key across 32 Feistel rounds. The smallest variant of the SIMON family.',
    defaultKey: '1918111009080100',
    defaultInput: '65656877',
    securityStatus: 'secure',
    keyPlaceholder: '64-bit key as 16 hex chars',
  },
  {
    id: 'tea',
    name: 'TEA',
    category: 'symmetric',
    description: 'The original 1994 predecessor to XTEA (also in this registry). Simple ARX Feistel cipher, no S-boxes — but has a documented equivalent-key weakness (4 related keys produce identical ciphertext), which XTEA\'s extra key mixing was designed specifically to fix.',
    defaultKey: '00000001000000020000000300000004',
    defaultInput: '0000000000000000',
    securityStatus: 'legacy',
    keyPlaceholder: '32-character hex key (128-bit)',
  },
  {
    id: 'noekeon',
    name: 'NOEKEON',
    category: 'symmetric',
    description: 'NESSIE-submitted 128-bit block cipher. Unique for having ZERO lookup tables; its non-linear Gamma layer uses exactly 5 bitwise AND/OR/XOR operations. Ideal for VLSI/FPGA environments.',
    defaultKey: '00000000000000000000000000000000',
    defaultInput: '00000000000000000000000000000000',
    securityStatus: 'secure',
    keyPlaceholder: '128-bit key as 32 hex chars',
  },
  {
    id: 'lea',
    name: 'LEA',
    category: 'symmetric',
    description: 'Korean lightweight ARX block cipher (IETF RFC 9998, 2024). Pure Add/Rotate/XOR — no S-boxes, making it 3–4× faster than AES on 32-bit processors. 128-bit block, 128/192/256-bit keys, 24/28/32 rounds. Used in Korean IoT and mobile applications.',
    defaultKey: '0f1e2d3c4b5a69788796a5b4c3d2e1f0',
    defaultInput: '101112131415161718191a1b1c1d1e1f',
    securityStatus: 'secure',
    keyPlaceholder: '128/192/256-bit key as 32/48/64 hex chars',
  },
  {
    id: 'gift',
    name: 'GIFT-64',
    category: 'symmetric',
    description: 'Ultra-lightweight 64-bit block cipher (CHES 2017). Uses a 4-bit S-box and 28-round SPN. 5x more hardware-efficient than PRESENT and underlies the NIST Lightweight Finalist GIFT-COFB.',
    defaultKey: '00000000000000000000000000000000',
    defaultInput: '0000000000000000',
    securityStatus: 'secure',
    keyPlaceholder: '128-bit key as 32 hex chars',
  },
  {
    id: 'xxtea',
    name: 'XXTEA',
    category: 'symmetric',
    description:
      'Corrected Block TEA (Wheeler & Needham, 1998). The final and strongest member of the TEA family. Unlike TEA/XTEA, it operates on the entire message as a single variable-length block (min 2 words) for full diffusion. Widely used historically but unauthenticated.',
    defaultKey: '00000000000000000000000000000000',
    defaultInput: '0000000000000000',
    securityStatus: 'legacy',
    keyPlaceholder: '128-bit key as 32 hex chars',
  },
  {
    id: 'blowfish',
    name: 'Blowfish',
    category: 'symmetric',
    description:
      'Bruce Schneier\'s 1993 Feistel block cipher — pre-AES era workhorse used in SSH, OpenSSH, and the bcrypt key schedule. Unique for its key-dependent S-box structure: the 4×256 S-boxes are entirely re-derived from each key, making it immune to weak-key attacks that plagued DES.',
    defaultKey: '0123456789abcdef',
    defaultInput: 'fedcba9876543210',
    securityStatus: 'legacy',
    keyPlaceholder: '4–56 byte key as hex (8–112 hex chars)',
  },
  {
    id: 'streebog',
    name: 'Streebog-256',
    category: 'hash',
    description:
      'Russian national hash function (GOST R 34.11-2012, RFC 6986). 512-bit internal state processed through 12 rounds of a Kuznyechik-family SPN in a Miyaguchi-Preneel-like compression function, with a unique checksum-based finalization step.',
    defaultKey: '',
    defaultInput: '323130393837363534333231303938373635343332313039383736353433323130393837363534333231303938373635343332313039383736353433323130',
    securityStatus: 'secure',
  },
  {
    id: 'seed',
    name: 'SEED-128',
    category: 'symmetric',
    description: 'Korean national block cipher (RFC 4269, 2005; ISO/IEC 18033-3). Mandatory in Korean financial and government systems for over a decade. 128-bit block, 128-bit key, 16-round Feistel with G-function using two GF(2^8)-derived S-boxes. Superseded by LEA for new Korean deployments.',
    defaultKey: '00000000000000000000000000000000',
    defaultInput: '000102030405060708090a0b0c0d0e0f',
    securityStatus: 'legacy',
    keyPlaceholder: '128-bit key as 32 hex chars',
  },
  {
    id: 'kuznyechik',
    name: 'Kuznyechik',
    category: 'symmetric',
    description:
      'Russian national block cipher (GOST R 34.12-2015, RFC 7801). 128-bit block, 256-bit key, 9-round SPN. Replaces the legacy 1989 GOST cipher. Uses a fixed 256-byte S-box and a linear transform built from 16 GF(2^8) feedback steps.',
    defaultKey: '8899aabbccddeeff0011223344556677fedcba98765432100123456789abcdef',
    defaultInput: '1122334455667700ffeeddccbbaa9988',
    securityStatus: 'secure',
    keyPlaceholder: '256-bit key as 64 hex chars',
  },
  {
    id: 'simon',
    name: 'SIMON-128/128',
    category: 'symmetric',
    description: "NSA hardware-optimised lightweight block cipher (IACR 2013/404). Sibling of SPECK — SIMON targets gate-minimal hardware via bitwise AND while SPECK targets software via ARX. 128-bit block, 128-bit key, 68-round Feistel. Round function: f(x)=(x<<<1 & x<<<8)⊕x<<<2.",
    defaultKey: '0f0e0d0c0b0a09080706050403020100',
    defaultInput: '6373656420737265' + '6c6c657661726174',
    securityStatus: 'secure',
    keyPlaceholder: '128-bit key as 32 hex chars',
  },
  {
    id: 'rabbit',
    name: 'Rabbit',
    category: 'symmetric',
    description:
      'eSTREAM Portfolio Phase 3 stream cipher (RFC 4503). 128-bit key, 64-bit IV. Distinctive non-linear counter system (no LFSR) using 64-bit squaring and XOR to generate 128 bits of keystream per iteration. Extremely fast in software.',
    defaultKey: '00000000000000000000000000000000',
    defaultInput: '00000000000000000000000000000000',
    securityStatus: 'secure',
    keyPlaceholder: '128-bit key as 32 hex chars',
  },
  {
    id: 'hc128',
    name: 'HC-128',
    category: 'symmetric',
    description: 'eSTREAM Phase 3 software-profile stream cipher by Hongjun Wu. Uses two 512-word (2 KB each) key/IV-derived lookup tables P and Q that update themselves during keystream generation. The fastest stream cipher in the eSTREAM portfolio on 32-bit software. Output = IV(32 hex) + ciphertext.',
    defaultKey: '00000000000000000000000000000000',
    defaultInput: '48656c6c6f20576f726c64',
    securityStatus: 'secure',
    keyPlaceholder: '128-bit key as 32 hex chars',
  },
  {
    id: 'anubis',
    name: 'Anubis',
    category: 'symmetric',
    description: 'NESSIE-submitted block cipher (2000). 128-bit block, 128/192/256-bit key. Unique involutional design: the S-box, diffusion layer, and round structure are all self-inverse. Decryption is literally the same code as encryption, just with reversed round keys.',
    defaultKey: '00000000000000000000000000000000',
    defaultInput: '00000000000000000000000000000000',
    securityStatus: 'secure',
    keyPlaceholder: '128/192/256-bit key as 32/48/64 hex chars',
  },
  {
    id: 'mars',
    name: 'MARS',
    category: 'symmetric',
    description:
      'IBM AES finalist (1998). 128-bit block, 32-round heterogeneous SPN. Unique for combining 4 different round types (forward mixing, forward E-rounds, backward E-rounds, backward mixing) for defense-in-depth. Lost to Rijndael (AES) on performance/simplicity, but unbroken.',
    defaultKey: '00000000000000000000000000000000',
    defaultInput: '00000000000000000000000000000000',
    securityStatus: 'secure',
    keyPlaceholder: '128/192/256-bit key as 32/48/64 hex chars',
  },
  {
    id: 'clefia',
    name: 'CLEFIA',
    category: 'symmetric',
    description: 'ISO/IEC 29192-2 lightweight block cipher (Sony, 2007). 4-branch generalized Feistel network (GFN) with parallel F0/F1 functions using distinct S-boxes and diffusion matrices. Pairs with PRESENT to complete the ISO lightweight standard duo.',
    defaultKey: 'ffeeddccbbaa99887766554433221100',
    defaultInput: '000102030405060708090a0b0c0d0e0f',
    securityStatus: 'secure',
    keyPlaceholder: '128/192/256-bit key as 32/48/64 hex chars',
  },
  {
    id: 'misty1',
    name: 'MISTY1',
    category: 'symmetric',
    description: 'CRYPTREC-recommended, RFC 2994. 64-bit block, 128-bit key. Unique recursive Feistel network: main rounds call FO, which calls FI, which uses 7-bit/9-bit S-boxes. Ancestor of KASUMI (3G/GSM).',
    defaultKey: '00112233445566778899aabbccddeeff',
    defaultInput: '0123456789abcdef',
    securityStatus: 'secure',
    keyPlaceholder: '128-bit key as 32 hex chars',
  },
  {
    id: 'square',
    name: 'Square',
    category: 'symmetric',
    description: 'Direct historical predecessor to Rijndael (AES) by Daemen & Rijmen (1997). Structurally defined the AES template but uses a distinct S-box and matrix. Status: BROKEN by the "Square attack" (integral cryptanalysis).',
    defaultKey: '00000000000000000000000000000000',
    defaultInput: '00000000000000000000000000000000',
    securityStatus: 'broken',
    keyPlaceholder: '128-bit key as 32 hex chars',
  },
  {
    id: 'feal',
    name: 'FEAL-8',
    category: 'symmetric',
    description: 'Japanese Feistel cipher (1987). Pure arithmetic design (no S-boxes). Status: BROKEN. Canonical target for differential cryptanalysis development. Included to demonstrate why differential characteristics are traceable in weak designs.',
    defaultKey: '0000000000000000',
    defaultInput: '0000000000000000',
    securityStatus: 'broken',
    keyPlaceholder: '64-bit key as 16 hex chars',
  },
  {
    id: 'safer-plus',
    name: 'SAFER+',
    category: 'symmetric',
    description: 'AES candidate (1998) and original Bluetooth pairing cipher. Byte-oriented SPN using modular exponentiation (45^x mod 257) for non-linearity and an Armenian Pseudo-Hadamard Transform network for diffusion.',
    defaultKey: '00000000000000000000000000000000',
    defaultInput: '00000000000000000000000000000000',
    securityStatus: 'legacy',
    keyPlaceholder: '128-bit key as 32 hex chars',
  },
  {
    id: 'aria',
    name: 'ARIA',
    category: 'symmetric',
    description: 'Korean national standard block cipher (KS X 1213, RFC 5794). AES-like SPN but alternates between two involutional S-box pairs (SB1/SB2) and uses a pure GF(2) involutional diffusion matrix. Completes the SEED/LEA/ARIA Korean trio.',
    defaultKey: '000102030405060708090a0b0c0d0e0f',
    defaultInput: '00112233445566778899aabbccddeeff',
    securityStatus: 'secure',
    keyPlaceholder: '128/192/256-bit key as 32/48/64 hex chars',
  },
  {
    id: 'kasumi',
    name: 'KASUMI',
    category: 'symmetric',
    description: '3GPP TS 35.202 (GSM A5/3, UMTS f8/f9). MISTY1-derived hardware-optimized cipher. Status: BROKEN (2010 related-key attack). Included for educational value as a once-deployed mobile standard.',
    defaultKey: '9900aabbccddeeff1122334455667788',
    defaultInput: 'fedcba0987654321',
    securityStatus: 'broken',
    keyPlaceholder: '128-bit key as 32 hex chars',
  },
  {
    id: 'grain128',
    name: 'Grain-128',
    category: 'symmetric',
    description: 'eSTREAM hardware-profile finalist (2006). Uses a coupled 128-bit LFSR and NLFSR. Distinctive initialization feeds output back into both registers for 256 rounds. Completes the eSTREAM hardware pairing alongside Trivium.',
    defaultKey: '00000000000000000000000000000000',
    defaultInput: '00',
    securityStatus: 'secure',
    keyPlaceholder: '128-bit key as 32 hex chars',
  },
  {
    id: '3way',
    name: '3-Way',
    category: 'symmetric',
    description: 'Joan Daemen\'s first cipher (1994). 96-bit block/key, 11 rounds. Defines three-fold cyclic symmetry where every sub-transform commutes with word rotation. Direct predecessor to Square and AES. Status: BROKEN.',
    defaultKey: '000000000000000000000000',
    defaultInput: '000000000000000000000000',
    securityStatus: 'broken',
    keyPlaceholder: '96-bit key as 24 hex chars',
  },
  {
    id: 'a5-1',
    name: 'A5/1',
    category: 'symmetric',
    description: 'Original GSM voice encryption (1987). Uses 3 LFSRs with irregular majority-vote clocking. Status: BROKEN. Comprehensively broken in real-world scenarios via rainbow tables. Predecessor to KASUMI/A5-3.',
    defaultKey: '0000000000000000',
    defaultInput: '00',
    securityStatus: 'broken',
    keyPlaceholder: '64-bit key as 16 hex chars',
  },
  {
    id: 'lucifer',
    name: 'Lucifer',
    category: 'symmetric',
    description: 'Horst Feistel\'s original cipher (~1971) and the namesake of the Feistel network. Direct predecessor to DES. Uniquely uses a key-controlled bit to select which of two S-boxes applies per byte. Status: BROKEN.',
    defaultKey: '00000000000000000000000000000000',
    defaultInput: '00000000000000000000000000000000',
    securityStatus: 'broken',
    keyPlaceholder: '128-bit key as 32 hex chars',
  },
  {
    id: 'deal',
    name: 'DEAL',
    category: 'symmetric',
    description: 'AES candidate (1998). 128-bit block Feistel network that uses full DES as its round function. Demonstrates building a larger cipher from an existing trusted primitive. Status: legacy.',
    defaultKey: '00000000000000000000000000000000',
    defaultInput: '00000000000000000000000000000000',
    securityStatus: 'legacy',
    keyPlaceholder: '128/192/256-bit key as 32/48/64 hex chars',
  },
  {
    id: 'des-x',
    name: 'DES-X',
    category: 'symmetric',
    description: 'Rivest\'s key-whitening extension of DES (1984). C = k2 XOR DES(k1, k0 XOR P). Demonstrates pure input/output whitening without modifying DES internals. Status: legacy (Kilian-Rogaway bound is weaker than naive 184-bit addition).',
    defaultKey: '00'.repeat(24),
    defaultInput: '0000000000000000',
    securityStatus: 'legacy',
    keyPlaceholder: '192-bit key as 48 hex chars (k0 + k1 + k2)',
  },
  {
    id: 'khufu',
    name: 'Khufu',
    category: 'symmetric',
    description: 'Ralph Merkle\'s 1990 block cipher. 64-bit block, 512-bit key. Defining feature: the 1KB S-box is entirely derived from the key, meaning every key uses a different substitution table. Status: legacy (64-bit block too small for modern use).',
    defaultKey: '00'.repeat(64),
    defaultInput: '0000000000000000',
    securityStatus: 'legacy',
    keyPlaceholder: '512-bit key as 128 hex chars',
  },
  {
    id: 'mickey',
    name: 'MICKEY',
    category: 'symmetric',
    description: 'eSTREAM hardware-profile finalist (2005). Uses mutual clock control: two registers (R, S) where EACH register\'s clocking decision depends on the OTHER\'s state simultaneously. Completes the eSTREAM hardware trio alongside Trivium and Grain-128.',
    defaultKey: '00000000000000000000000000000000',
    defaultInput: '00',
    securityStatus: 'secure',
    keyPlaceholder: '128-bit key as 32 hex chars',
  },
  {
    id: 'kalyna',
    name: 'Kalyna',
    category: 'symmetric',
    description: 'Ukrainian national block cipher (DSTU 7624:2014). AES-family SPN supporting 128/256/512-bit blocks. Uses 4 distinct S-boxes applied in a round-dependent pattern. Begins Ukrainian national-suite representation.',
    defaultKey: '00000000000000000000000000000000',
    defaultInput: '00000000000000000000000000000000',
    securityStatus: 'secure',
    keyPlaceholder: 'Key (equal or double block size)',
    options: [
      { name: 'Block Size', id: 'blockSize', type: 'select', default: 128, choices: [{label: '128', value: 128}, {label: '256', value: 256}, {label: '512', value: 512}] }
    ]
  },
  {
    id: 'zuc',
    name: 'ZUC',
    category: 'symmetric',
    description: 'Chinese national stream cipher (GB/T 33133). Used in 4G LTE (128-EEA3). Uniquely uses a 16-stage LFSR over GF(2^31-1) with modular arithmetic, NOT simple XOR feedback. Completes the SM2/SM3/SM4/ZUC national suite.',
    defaultKey: '00000000000000000000000000000000',
    defaultInput: '00000000',
    securityStatus: 'secure',
    keyPlaceholder: '128-bit key as 32 hex chars',
  },
  {
    id: 'sosemanuk',
    name: 'SOSEMANUK',
    category: 'symmetric',
    description: 'eSTREAM software-profile finalist (2005). Combines a 10-stage GF(2^32) LFSR with a Serpent-derived nonlinear FSM. Completes the eSTREAM software quartet alongside HC-128, Rabbit, and Salsa20.',
    defaultKey: '00000000000000000000000000000000',
    defaultInput: '00000000',
    securityStatus: 'secure',
    keyPlaceholder: '128/256-bit key as 32/64 hex chars',
  },
  {
    id: 'loki97',
    name: 'LOKI97',
    category: 'symmetric',
    description: 'Australian AES candidate (1998). Uniquely uses exponentiation in GF(2^64) to generate its S-box non-linearity, a fundamentally different algebraic source than the GF(2^8) tables used by AES/SM4/ARIA. Status: legacy.',
    defaultKey: '00000000000000000000000000000000',
    defaultInput: '00000000000000000000000000000000',
    securityStatus: 'legacy',
    keyPlaceholder: '128/192/256-bit key as 32/48/64 hex chars',
  },
  {
    id: 'seal',
    name: 'SEAL',
    category: 'symmetric',
    description: 'Software-optimized stream cipher (Rogaway & Coppersmith, 1993). Implements SEAL 3.0 (corrected). All cryptographic work front-loaded into one-time SHA-1-derived table setup; keystream generation is pure table lookup with ZERO further mixing. Contrasts with HC-128\'s self-updating tables. Status: legacy (age, fixed 160-bit key).',
    defaultKey: '0000000000000000000000000000000000000000',
    defaultInput: '0000000000000000',
    securityStatus: 'legacy',
    keyPlaceholder: '160-bit key as 40 hex chars',
    keySize: '160',
  },
  {
    id: 'shark',
    name: 'SHARK',
    category: 'symmetric',
    description: 'Earliest predecessor in the SHARK->Square->AES lineage (1996). 64-bit block, full 8x8 MDS diffusion every round. Status: broken (vulnerable to same integral attacks as Square).',
    defaultKey: '00000000000000000000000000000000',
    defaultInput: '0000000000000000',
    securityStatus: 'broken',
    keyPlaceholder: '128-bit key as 32 hex chars',
  },
  {
    id: 'turing',
    name: 'Turing',
    category: 'symmetric',
    description: 'NESSIE-submitted software-speed stream cipher (Rose & Hawkes, 2003). COMPLETELY FIXED 17-stage GF(2^32) LFSR + COMPLETELY FIXED S-box nonlinear filter — neither self-updates (unlike HC-128) nor is externally hash-derived (unlike SEAL). Status: legacy.',
    defaultKey: '00000000000000000000000000000000',
    defaultInput: '0000000000000000',
    securityStatus: 'legacy',
    keyPlaceholder: '128/160/256-bit key as 32/40/64 hex chars',
    keySize: '128/160/256',
  },
  {
    id: 'crypton',
    name: 'Crypton',
    category: 'symmetric',
    description: 'Korean AES competition submission (1998) — NOT a Korean national standard (distinct from SEED/LEA/ARIA which are official standards). Uses 2 S-box types × 4 position variants and a bit-permutation diffusion layer distinct from AES\'s ShiftRows+MixColumns. Status: legacy (first-round elimination, limited scrutiny).',
    defaultKey: '00000000000000000000000000000000',
    defaultInput: '00000000000000000000000000000000',
    securityStatus: 'legacy',
    keyPlaceholder: '128/192/256-bit key as 32/48/64 hex chars',
    keySize: '128/192/256',
  },
  {
    id: 'wake',
    name: 'WAKE',
    category: 'symmetric',
    description: 'Word Auto Key Encryption (David Wheeler, 1993). Stream cipher with a 256-entry 32-bit table that is CONTINUOUSLY UPDATED during keystream generation — each output word feeds back to overwrite a table entry, making the table data-dependent. Distinct from HC-128/SEAL/Turing. Status: legacy.',
    defaultKey: '00000000000000000000000000000000',
    defaultInput: '0000000000000000',
    securityStatus: 'legacy',
    keyPlaceholder: '128-bit key as 32 hex chars',
    keySize: '128',
  },
  {
    id: 'hierocrypt3',
    name: 'Hierocrypt-3',
    category: 'symmetric',
    description: 'Toshiba CRYPTREC candidate (2000). Distinctive NESTED SPN: each outer round contains TWO XS-box sub-layers (byte substitution + small internal MDS diffusion) with outer MDS-L diffusion between them — two distinct diffusion scales within one round. Status: legacy (lower CRYPTREC tier than Camellia).',
    defaultKey: '00000000000000000000000000000000',
    defaultInput: '00000000000000000000000000000000',
    securityStatus: 'legacy',
    keyPlaceholder: '128/192/256-bit key as 32/48/64 hex chars',
    keySize: '128/192/256',
  },
  {
    id: 'e2',
    name: 'E2',
    category: 'symmetric',
    description: 'NTT AES Round 1 candidate (1998). Direct historical predecessor to Camellia. 128-bit Feistel with byte-oriented S-box + BRL binary matrix diffusion, plus outer whitening layers. Status: legacy (superseded by Camellia).',
    defaultKey: '00000000000000000000000000000000',
    defaultInput: '00000000000000000000000000000000',
    securityStatus: 'legacy',
    keyPlaceholder: '128/192/256-bit key as 32/48/64 hex chars',
    keySize: '128/192/256',
  },
  {
    id: "sha256",
    name: "SHA-256",
    category: "hash",
    description:
      "Secure Hash Algorithm 2. Produces a unique 256-bit hash output representing the input message.",
    defaultKey: "",
    defaultInput: "abc",
    securityStatus: "recommended",
    keySize: "None (hash function)",
    practicalUseCases: ["Data integrity verification", "Digital signatures", "Blockchain proof-of-work", "Password hashing (via HMAC/PBKDF2)"],
    recommendedNext: ["hmac", "sha512", "bcrypt"],
  },
  {
    id: "sha512",
    name: "SHA-512",
    category: "hash",
    description:
      "Secure Hash Algorithm 2 with 64-bit words, producing a secure 512-bit digest.",
    defaultKey: "",
    defaultInput: "abc",
    securityStatus: "secure",
    prerequisites: ["sha256"],
    recommendedNext: ["hmac", "hkdf", "bcrypt"],
  },
  {
    id: "sm3",
    name: "SM3 Hash",
    category: "hash",
    description:
      "Chinese National Standard cryptographic hash function (GB/T 32905-2016). Produces a 256-bit message digest using 64 ARX compression rounds.",
    defaultKey: "",
    defaultInput: "abc",
    securityStatus: "secure",
  },
  {
    id: "md5",
    name: "MD5",
    category: "hash",
    description:
      "A widely used legacy hash producing a 128-bit output. Cryptographically broken due to collision vulnerabilities.",
    defaultKey: "",
    defaultInput: "abc",
    securityStatus: "broken",
  },
  {
    id: "hmac",
    name: "HMAC-SHA256",
    category: "hash",
    description:
      "Keyed-hash Message Authentication Code. Combines SHA-256 with a cryptographic secret key.",
    defaultKey: "Jefe",
    defaultInput: "what do ya want for nothing?",
    securityStatus: "secure",
    keyPlaceholder: "HMAC Secret Key",
    prerequisites: ["sha256"],
    recommendedNext: ["hkdf", "bcrypt", "rsa"],
  },
  {
    id: 'cmac',
    name: 'AES-CMAC',
    category: 'hash',
    description: 'A MAC built entirely from AES block-cipher calls plus a GF(2^128) subkey-derivation step (NIST SP 800-38B) — no separate hash function, unlike HMAC. Composed from the existing AES module, no new dependencies.',
    defaultKey: '2b7e151628aed2a6abf7158809cf4f3c',
    defaultInput: '6bc1bee22e409f96e93d7e117393172a',
    securityStatus: 'secure',
  },
  {
    id: "bcrypt",
    name: "Bcrypt",
    category: "hash",
    description:
      "A password hashing function incorporating a salt and cost factor, designed to be slow to prevent brute force.",
    defaultKey: "password",
    defaultInput: "password",
    securityStatus: "recommended",
    prerequisites: ["sha256", "hmac"],
    recommendedNext: ["hkdf", "rsa"],
    options: [
      {
        name: "Rounds (Cost)",
        id: "rounds",
        type: "number",
        default: 4,
      },
    ],
  },
  {
    id: "xxhash",
    name: "XXHash32",
    category: "hash",
    description:
      "A very fast non-cryptographic 32-bit hash used for checksums, hash tables, and data integrity demos.",
    defaultKey: "0",
    defaultInput: "Hello, World!",
    securityStatus: "deprecated",
    keyPlaceholder: "Unsigned 32-bit seed (e.g. 0 or 0x1)",
    options: [
      {
        name: "Input Encoding",
        id: "encoding",
        type: "select",
        default: "utf8",
        choices: [
          { label: "UTF-8 text", value: "utf8" },
          { label: "Hex bytes", value: "hex" },
          { label: "Base64", value: "base64" },
          { label: "Binary bytes", value: "binary" },
        ],
      },
    ],
  },
  {
    id: 'bloom-filter',
    name: 'Bloom Filter Simulator',
    category: 'hash',
    description: 'A space-efficient probabilistic data structure testing set membership with zero false negatives and a tunable false-positive probability.',
    defaultKey: '3',
    defaultInput: 'phishing-bank-login.com',
    securityStatus: 'secure',
    keyPlaceholder: 'Number of hash functions k (e.g. 3)',
    options: [
      {
        name: 'Bit Array Size (m)',
        id: 'size',
        type: 'number',
        default: 64,
      },
      {
        name: 'Hash Functions (k)',
        id: 'numHashes',
        type: 'number',
        default: 3,
      },
    ],
  },
  {
    id: 'hkdf',
    name: 'HKDF (HMAC Key Derivation)',
    category: 'hash',
    description: 'HMAC-based Extract-and-Expand Key Derivation Function (RFC 5869) that converts weak or shared input keying material into cryptographically strong output keys.',
    defaultKey: '000102030405060708090a0b0c',
    defaultInput: '0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b',
    securityStatus: 'secure',
    keyPlaceholder: 'Salt hex or text (optional)',
    options: [
      {
        name: 'Hash Function',
        id: 'hash',
        type: 'select',
        default: 'SHA-256',
        choices: [
          { label: 'SHA-256 (32-byte HashLen)', value: 'SHA-256' },
          { label: 'SHA-512 (64-byte HashLen)', value: 'SHA-512' },
          { label: 'SHA-1 (20-byte HashLen)', value: 'SHA-1' },
        ],
      },
      {
        name: 'Context Info (info)',
        id: 'info',
        type: 'text',
        default: 'f0f1f2f3f4f5f6f7f8f9',
      },
      {
        name: 'Derived Key Length (L bytes)',
        id: 'keyLength',
        type: 'number',
        default: 42,
      },
    ],
  },
  {
    id: 'blake2s',
    name: 'BLAKE2s',
    category: 'hash',
    description: 'The 32-bit-word sibling of BLAKE2b (2012), optimized for 8- to 32-bit platforms — smaller blocks, fewer rounds, 256-bit max output. Used internally by Argon2.',
    defaultKey: '',
    defaultInput: 'abc',
    securityStatus: 'secure',
  },
  {
    id: 'sha224',
    name: 'SHA-224',
    category: 'hash',
    description: 'A truncated SHA-2 family member (FIPS 180-4) with its OWN initial hash value — not simply SHA-256\'s output cut short, which is a deliberate design choice to prevent leaking one digest from the other.',
    defaultKey: '',
    defaultInput: 'abc',
    securityStatus: 'secure',
  },
  {
    id: 'sha384',
    name: 'SHA-384',
    category: 'hash',
    description: 'The 384-bit truncated member of the SHA-512 family (FIPS 180-4), with its own distinct initial hash value, same design principle as SHA-224 relative to SHA-256.',
    defaultKey: '',
    defaultInput: 'abc',
    securityStatus: 'secure',
  },
  {
    id: 'shake128',
    name: 'SHAKE128',
    category: 'hash',
    description: 'An extendable-output function (XOF, NIST FIPS 202) — unlike every other hash here, output length is a parameter you choose, not fixed. Same Keccak permutation family as SHA-3.',
    defaultKey: '32',
    defaultInput: 'abc',
    securityStatus: 'experimental',
    keyPlaceholder: 'requested output length in bytes (default 32)',
  },
  {
    id: 'shake256',
    name: 'SHAKE256',
    category: 'hash',
    description: 'The wider-capacity sibling of SHAKE128 (NIST FIPS 202) — same extendable-output design, larger security margin.',
    defaultKey: '32',
    defaultInput: 'abc',
    securityStatus: 'experimental',
    keyPlaceholder: 'requested output length in bytes (default 32)',
  },
  {
    id: 'pbkdf2',
    name: 'PBKDF2',
    category: 'hash',
    description: 'RFC 8018 (PKCS #5). The most widely deployed KDF in the world (WPA2, iOS keychain). Iteratively applies HMAC to a password+salt. Slower iteration counts increase brute-force resistance.',
    defaultKey: 'salt',
    defaultInput: 'password',
    securityStatus: 'secure',
    keyPlaceholder: 'Salt',
    options: [
      { name: 'Iterations (c)', id: 'iterations', type: 'number', default: 600000 },
      { name: 'Output Length (dkLen)', id: 'keyLength', type: 'number', default: 32 }
    ]
  },
  {
    id: 'md4',
    name: 'MD4',
    category: 'hash',
    description: 'The direct predecessor to MD5 (1990) — fully broken today. Simpler than MD5: only 3 rounds (vs MD5\'s 4) and no additive per-step constants, illustrating exactly what MD5 was designed to fix.',
    defaultKey: '',
    defaultInput: 'abc',
    securityStatus: 'broken',
  },
  {
    id: 'argon2',
    name: 'Argon2id',
    category: 'hash',
    description: 'PHC Winner (2015), RFC 9106. Memory-hard password hashing with hybrid addressing (Argon2i for side-channel resistance, Argon2d for GPU resistance). Modern successor to bcrypt.',
    defaultKey: 'salt',
    defaultInput: 'password',
    securityStatus: 'secure',
    keyPlaceholder: 'Salt (min 8 bytes)',
    options: [
      { name: 'Memory Cost (KiB)', id: 'memoryCost', type: 'number', default: 19456 },
      { name: 'Time Cost (Iterations)', id: 'timeCost', type: 'number', default: 2 },
      { name: 'Parallelism', id: 'parallelism', type: 'number', default: 1 },
      { name: 'Output Length (bytes)', id: 'keyLength', type: 'number', default: 32 }
    ]
  },
  {
    id: 'skein',
    name: 'Skein-256',
    category: 'hash',
    description: "SHA-3 finalist (Skein v1.3, 2010) by Schneier et al. Built on Threefish-256 via UBI (Unique Block Iteration) chaining — a Davies-Meyer construction. Pipeline: Config → Message → Output. Each block encrypted with Threefish-256 then XORed with plaintext. 256-bit output.",
    defaultKey: '',
    defaultInput: '48656c6c6f20576f726c64',
    securityStatus: 'secure',
    keyPlaceholder: '(no key — this is a hash function)',
  },
  {
    id: 'lsh256',
    name: 'LSH-256',
    category: 'hash',
    description: 'Korean national hash standard (KS X 3262, 2014). Wide-pipe ARX+Boolean design with 1024-bit internal state. Completes the SEED/LEA/ARIA/LSH Korean cryptographic suite.',
    defaultKey: '',
    defaultInput: '',
    securityStatus: 'secure',
  },
  {
    id: 'tiger',
    name: 'Tiger',
    category: 'hash',
    description: 'Fast 192-bit hash designed for 64-bit processors (Anderson & Biham, 1995). Uses three 64-bit chaining variables and 3 passes of 8 rounds over four 256-entry 64-bit S-boxes. Fills the 192-bit output gap in this repo.',
    defaultKey: '',
    defaultInput: '616263',
    securityStatus: 'secure',
  },
  {
    id: 'grostl',
    name: 'Grøstl-256',
    category: 'hash',
    description: 'SHA-3 finalist (2008). AES-based wide-pipe hash using dual permutations P and Q in a Davies-Meyer-like compression function. Operates on an 8x8 byte state with AES-style SubBytes/ShiftBytes/MixBytes rounds.',
    defaultKey: '',
    defaultInput: '',
    securityStatus: 'secure',
  },
  {
    id: 'jh',
    name: 'JH-256',
    category: 'hash',
    description: 'SHA-3 finalist (2008). Fixed 1024-bit permutation with generalized AES-like rounds using 4-bit S-boxes and bit-level grouping permutation. Double message XOR injection. Completes the five-of-five SHA-3 finalist set.',
    defaultKey: '',
    defaultInput: '',
    securityStatus: 'secure',
  },
  {
    id: 'ripemd128',
    name: 'RIPEMD-128',
    category: 'hash',
    description: '128-bit output sibling of RIPEMD-160. Dual-parallel-line MD4-family design with distinct tables from its 160-bit counterpart. Status: legacy (128-bit output too short for modern collision resistance).',
    defaultKey: '',
    defaultInput: '',
    securityStatus: 'legacy',
  },
  {
    id: 'haval',
    name: 'HAVAL',
    category: 'hash',
    description: 'Configurable hash (1992). Unique in offering independent control over round count (3/4/5 passes) and output length (128-256 bits). Status: legacy (weaker at 3-pass/128-bit, stronger at 5-pass/256-bit).',
    defaultKey: '',
    defaultInput: '',
    securityStatus: 'legacy',
    options: [
      { name: 'Passes (Rounds)', id: 'passes', type: 'select', default: 5, choices: [{label: '3', value: 3}, {label: '4', value: 4}, {label: '5', value: 5}] },
      { name: 'Output Length (bits)', id: 'outputBits', type: 'select', default: 256, choices: [{label: '128', value: 128}, {label: '160', value: 160}, {label: '192', value: 192}, {label: '224', value: 224}, {label: '256', value: 256}] }
    ]
  },
  {
    id: 'md2',
    name: 'MD2',
    category: 'hash',
    description: 'Earliest MD-family hash (RFC 1319, 1989). Byte-oriented with a distinctive 16-byte checksum block appended before compression. Status: BROKEN (severe weaknesses). Completes the MD2->MD4->MD5 lineage.',
    defaultKey: '',
    defaultInput: '',
    securityStatus: 'broken',
  },
  {
    id: 'gost-r34-11-94',
    name: 'GOST R 34.11-94',
    category: 'hash',
    description: 'Original Russian national hash standard (1994-2013). Uses GOST 28147-89 block cipher internally with a distinctive P-transformation key-mixing step. Superseded by Streebog. Status: legacy.',
    defaultKey: '',
    defaultInput: '',
    securityStatus: 'legacy',
  },
  {
    id: 'n-hash',
    name: 'N-Hash',
    category: 'hash',
    description: 'NTT Japan hash (1990). Uses FEAL-style addition-and-rotation nonlinearity in a Davies-Meyer construction. NO S-BOXES. Status: BROKEN (differential cryptanalysis, shared lineage with FEAL).',
    defaultKey: '',
    defaultInput: '',
    securityStatus: 'broken',
  },
  {
    id: 'snefru',
    name: 'Snefru',
    category: 'hash',
    description: 'Merkle\'s 1990 hash design. Uses 4 large 256x32-bit S-boxes. Configurable passes (2/4) and output (128/256). Status: legacy (2-pass is weak, 4-pass is stronger). Complements Merkle-Hellman in the repo.',
    defaultKey: '',
    defaultInput: '',
    securityStatus: 'legacy',
    options: [
      { name: 'Passes', id: 'passes', type: 'select', default: 2, choices: [{label: '2', value: 2}, {label: '4', value: 4}] },
      { name: 'Output Length (bits)', id: 'outputBits', type: 'select', default: 128, choices: [{label: '128', value: 128}, {label: '256', value: 256}] }
    ]
  },
  {
    id: 'has160',
    name: 'HAS-160',
    category: 'hash',
    description: 'Korean national hash standard (TTAS.KO-12.0011). Structurally similar to SHA-1 but with distinct message scheduling and constants. Originally specified to pair with KCDSA. Status: legacy (160-bit output).',
    defaultKey: '',
    defaultInput: '',
    securityStatus: 'legacy',
  },
  {
    id: 'panama',
    name: 'Panama',
    category: 'hash',
    description: 'Daemen & Clapp (1998). Dual-mode primitive (Hash/Stream). This visualizer covers Hash mode only. Uses a massive 32-stage buffer + 17-word state. Daemen-lineage connection to 3-Way/Square. Status: legacy.',
    defaultKey: '',
    defaultInput: '',
    securityStatus: 'legacy',
  },
  {
    id: 'blake',
    name: 'BLAKE',
    category: 'hash',
    description: 'The ORIGINAL 2008 SHA-3 finalist. Uses HAIFA construction (explicit counter/salt per block) and ChaCha-lineage ARX compression. Distinct from the later, independently-designed BLAKE2/BLAKE3 descendants.',
    defaultKey: '',
    defaultInput: '',
    securityStatus: 'secure',
  },
  {
    id: 'kupyna',
    name: 'Kupyna',
    category: 'hash',
    description: 'Ukrainian national hash standard (DSTU 7564:2014). Uses Kalyna\'s SPN round structure in a Davies-Meyer construction. Completes the Ukrainian national suite alongside Kalyna.',
    defaultKey: '',
    defaultInput: '',
    securityStatus: 'secure',
    options: [
      { name: 'Output Length (bits)', id: 'outputBits', type: 'select', default: 256, choices: [{label: '256', value: 256}, {label: '512', value: 512}] }
    ]
  },
  {
    id: 'radiogatun',
    name: 'RadioGatun',
    category: 'hash',
    description: 'Sponge-construction hash (Bertoni, Daemen, Peeters, Van Assche, 2006). DIRECT PREDECESSOR TO KECCAK (SHA-3 winner). Introduced the sponge construction in essentially final form: mill (small nonlinear state) + belt (larger diffusion array). Distinct from Panama (different state shape, dual hash/stream mode). No successful attack documented. Status: secure.',
    defaultKey: '',
    defaultInput: '',
    securityStatus: 'secure',
    options: [
      {
        name: 'Output Length (bits)',
        id: 'outputBits',
        type: 'select',
        default: 256,
        choices: [
          { label: '128', value: 128 },
          { label: '256', value: 256 },
          { label: '512', value: 512 },
        ]
      }
    ],
  },
  {
    id: 'ascon-hash',
    name: 'Ascon-Hash',
    category: 'hash',
    description: 'NIST Lightweight Cryptography Standard (SP 800-232, 2025). SPONGE MODE using the SAME Ascon permutation already implemented in ascon.ts for AEAD mode. Genuinely reuses the 5x64-bit-word permutation — only the surrounding construction differs (sponge absorb-then-squeeze vs. AEAD duplex). Status: secure.',
    defaultKey: '',
    defaultInput: '',
    securityStatus: 'secure',
  },
  {
    id: 'kangarootwelve',
    name: 'KangarooTwelve',
    category: 'hash',
    description: 'Fast tree-hashing XOF (Bertoni, Daemen et al., 2016). GENUINE REUSE of sha3.ts Keccak-p permutation, parameterized for 12 rounds instead of 24. TREE-HASHING STRUCTURE: input split into 8192-byte chunks processed independently (in principle, in parallel), then combined via root computation. Fundamentally different from sequential hashes. IRTF-documented. Status: secure.',
    defaultKey: '',
    defaultInput: '',
    securityStatus: 'secure',
    options: [
      {
        name: 'Output Length (bytes)',
        id: 'outputLength',
        type: 'number',
        default: 32,
      }
    ],
  },
  // Asymmetric
  {
    id: "rsa",
    name: "RSA-2048",
    category: "asymmetric",
    description:
      "An asymmetric cipher based on the difficulty of factoring large semiprimes. Supports key generation, encryption, and decryption.",
    defaultKey: "61,53,17",
    defaultInput: "HELLO",
    securityStatus: "secure",
    keyPlaceholder:
      "Enter: 3 values (p,q,e) or 2 values (n,e / n,d) if you already have n",
    keySize: "Typically 2048 to 4096 bits",
    practicalUseCases: ["Secure key exchange", "Digital signatures", "Secure email (PGP/S/MIME)", "SSL/TLS certificates"],
    prerequisites: ["hmac"],
    recommendedNext: ["ecc", "dh", "ml-kem"],
    options: [
      {
        name: "Input Encoding Mode",
        id: "inputEncoding",
        type: "select",
        default: "integer",
        choices: [
          { label: "Raw Math Integer (M < n)", value: "integer" },
          { label: "UTF-8 Text Stream", value: "text" },
          { label: "Hex Bytes", value: "hex" },
        ],
      },
      {
        name: "Demo Mode (Small Primes)",
        id: "demoMode",
        type: "boolean",
        default: true,
      },
    ],
  },
  {
    id: 'dsa',
    name: 'DSA',
    category: 'asymmetric',
    description: 'The finite-field discrete-log ancestor of ECDSA (NIST FIPS 186, 1994) — same r/s signature equation, computed in a prime-order subgroup instead of on a curve. Demo uses toy parameters; real DSA needs p>=2048 bits, q>=224 bits.',
    defaultKey: '47,23,4,5',
    defaultInput: '15',
    securityStatus: 'secure',
    keyPlaceholder: 'p,q,g,x (private, sign) or p,q,g,y (public, verify)',
  },
  {
    id: "dh",
    name: "Diffie-Hellman",
    category: "asymmetric",
    description:
      "A key exchange protocol enabling two parties to establish a shared secret over an insecure channel.",
    defaultKey: "23,5",
    defaultInput: "6,15",
    securityStatus: "secure",
    keyPlaceholder: "p,g parameters (e.g. 23,5)",
    prerequisites: ["rsa"],
    recommendedNext: ["ecc", "x448", "ml-kem"],
    options: [
      {
        name: "Bob Secret input (demo)",
        id: "bobSecret",
        type: "text",
        default: "15",
      },
    ],
  },
  {
    id: 'x448',
    name: 'X448',
    category: 'asymmetric',
    description: 'Diffie-Hellman key exchange over Curve448 (RFC 7748) — the higher-security sibling of X25519, targeting ~224-bit security with 56-byte keys instead of X25519\'s 32-byte keys.',
    defaultKey: '',
    defaultInput: '',
    securityStatus: 'secure',
    keyPlaceholder: '56-byte private key hex (112 chars), or leave blank to generate one',
  },
  {
    id: "ecc",
    name: "ECC (ECDSA P-256)",
    category: "asymmetric",
    description:
      "Elliptic Curve Cryptography. Implements ECDSA signing and verification over the NIST P-256 curve.",
    defaultKey:
      "0102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20",
    defaultInput: "hello",
    securityStatus: "secure",
    keyPlaceholder: "32-byte private key hex (64 chars)",
    prerequisites: ["rsa", "dh"],
    recommendedNext: ["schnorr", "ml-dsa", "ml-kem"],
  },
  {
    id: 'schnorr',
    name: 'Schnorr (BIP340)',
    category: 'asymmetric',
    description: 'Schnorr signatures per BIP340 over secp256k1, using x-only public keys. Provably secure under a simpler assumption than ECDSA and supports clean signature aggregation (MuSig) — compare against ecdsa.ts on the same curve.',
    defaultKey: '',
    defaultInput: 'hello',
    securityStatus: 'secure',
    keyPlaceholder: '32-byte private key hex (64 chars), or leave blank to generate one',
  },
  {
    id: 'elgamal-signature',
    name: 'ElGamal Signature',
    category: 'asymmetric',
    description: 'The ElGamal signature scheme (1985) — distinct from ElGamal encryption already in this registry. Historically the direct ancestor of DSA: DSA is this scheme computed in a smaller prime-order subgroup for shorter signatures.',
    defaultKey: '467,2,127',
    defaultInput: '100',
    securityStatus: 'secure',
    keyPlaceholder: 'p,g,x (private, sign) or p,g,y (public, verify)',
  },
  {
    id: 'ml-dsa',
    name: 'ML-DSA-65',
    category: 'asymmetric',
    description: 'Post-quantum digital signatures (NIST FIPS 204, formerly Dilithium), pairing with ML-KEM the same way Ed25519 pairs with X25519 classically — except the hard problem here is lattice-based (Module-LWE/SIS), not elliptic-curve discrete log.',
    defaultKey: '',
    defaultInput: 'hello',
    securityStatus: 'secure',
    keyPlaceholder: 'private key (sign) or "publicKey|signature" (verify)',
    prerequisites: ["ecc"],
    recommendedNext: ["ml-kem"],
  },
  {
    id: 'ecies',
    name: 'ECIES (X25519)',
    category: 'asymmetric',
    description: 'Hybrid encryption: ephemeral X25519 key agreement + HKDF + AEAD, letting a sender encrypt an arbitrary-length message directly to a recipient\'s public key — no other asymmetric module here does this end-to-end.',
    defaultKey: '',
    defaultInput: 'A secret message for the recipient',
    securityStatus: 'secure',
    keyPlaceholder: 'recipient X25519 public key (encrypt) or your private key (decrypt)',
  },
  {
    id: 'ml-kem',
    name: 'ML-KEM-768',
    category: 'asymmetric',
    description: 'Post-quantum key encapsulation (NIST FIPS 203, formerly Kyber), based on the Module Learning With Errors lattice problem — secure against both classical and quantum attackers, unlike every other asymmetric module here.',
    defaultKey: '',
    defaultInput: '',
    securityStatus: 'secure',
    keyPlaceholder: 'recipient public key (encapsulate) or private key (decapsulate)',
    prerequisites: ["ecc", "dh"],
    recommendedNext: ["frodokem", "ml-dsa", "ecies"],
  },
  {
    id: 'frodokem',
    name: 'FrodoKEM-640',
    category: 'asymmetric',
    description: 'Post-quantum key encapsulation mechanism (KEM) based on unstructured Learning With Errors (LWE) on standard matrices, offering conservative security without algebraic ring assumptions.',
    defaultKey: '',
    defaultInput: '',
    securityStatus: 'secure',
    keyPlaceholder: 'recipient public key JSON (encapsulate) or private key JSON (decapsulate)',
    prerequisites: ["ml-kem", "ecc"],
    recommendedNext: ["ml-dsa", "ntru"],
  },
  {
    id: 'ed448',
    name: 'Ed448',
    category: 'asymmetric',
    description: 'EdDSA signatures over Curve448 (RFC 8032) — the higher-security-margin sibling of Ed25519, using SHAKE256 internally instead of SHA-512. Completes the Curve25519/Curve448 x agreement/signing grid alongside x25519, x448, and ed25519.',
    defaultKey: '',
    defaultInput: 'hello',
    securityStatus: 'secure',
    keyPlaceholder: '57-byte private key hex (114 chars), or leave blank to generate one',
  },
  {
    id: 'shamir-secret-sharing',
    name: "Shamir's Secret Sharing",
    category: 'asymmetric',
    description: 'A threshold scheme (1979): splits a secret into N shares such that any K reconstruct it, but K-1 reveal nothing. Uses GF(256) polynomial arithmetic — a different mathematical toolkit from every other module here.',
    defaultKey: '5,3',
    defaultInput: 'deadbeef',
    securityStatus: 'secure',
    keyPlaceholder: 'totalShares,threshold (split) — leave blank for combine',
  },
  {
    id: 'sidh',
    name: 'SIDH',
    category: 'asymmetric',
    description: 'Isogeny-based key exchange (SIKE). Status: FULLY BROKEN (2022). Included as an educational case study demonstrating how a promising NIST PQC candidate was completely broken via classical mathematics exploiting auxiliary torsion-point data.',
    defaultKey: 'pub,priv',
    defaultInput: '01',
    securityStatus: 'broken',
    keyPlaceholder: 'Public key (encrypt) or Private key (decrypt)',
  },
  {
    id: 'ntru',
    name: 'NTRU',
    category: 'asymmetric',
    description: 'Lattice-based public-key cryptosystem (IEEE P1363.1, 1996). Operates in polynomial ring Z[x]/(x^N-1). Predates NIST PQC by 20+ years. WARNING: Visualizer uses small pedagogical parameters (N=11) for teaching; NOT secure at this size.',
    defaultKey: 'pub,priv',
    defaultInput: '01',
    securityStatus: 'secure',
    keyPlaceholder: 'Public key (encrypt) or Private key (decrypt)',
  },
  {
    id: 'gost-r34-10',
    name: 'GOST R 34.10-2012',
    category: 'asymmetric',
    description: 'Russian national elliptic-curve signature standard (RFC 7091). Uses Streebog-256 and an addition-based signing equation with a unique e=0 -> e=1 edge case. Completes the GOST/Kuznyechik/Streebog Russian suite.',
    defaultKey: '1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef',
    defaultInput: 'message',
    securityStatus: 'secure',
    keyPlaceholder: 'Private key (sign) or Public key (verify)',
  },
  {
    id: 'mceliece',
    name: 'Classic McEliece',
    category: 'asymmetric',
    description: 'Code-based Post-Quantum KEM (NIST PQC Finalist, 1978). Security rests on decoding random linear codes. WARNING: Visualizer uses small pedagogical parameters (n=15) for teaching; NOT secure at this size. Real McEliece has an exceptionally long unbroken track record.',
    defaultKey: 'pub,priv',
    defaultInput: '01',
    securityStatus: 'secure',
    keyPlaceholder: 'Public key (encrypt) or Private key (decrypt)',
  },
  {
    id: 'cramer-shoup',
    name: 'Cramer-Shoup',
    category: 'asymmetric',
    description: 'First practical IND-CCA2-secure public-key scheme in the standard model (1998). Extends ElGamal with 5 secret exponents and a hash-based integrity check that rejects tampered ciphertexts.',
    defaultKey: 'mock_keys',
    defaultInput: '0000000000000001',
    securityStatus: 'secure',
    keyPlaceholder: 'Public key (encrypt) or Private key (decrypt)',
  },
  {
    id: 'sm2',
    name: 'SM2',
    category: 'asymmetric',
    description: 'Chinese national elliptic-curve signature standard (GB/T 32918). Uses a distinct ZA hash prefix incorporating the signer ID and curve parameters before hashing the message. Completes the SM2+SM3+SM4 Chinese suite.',
    defaultKey: '1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef',
    defaultInput: 'message',
    securityStatus: 'secure',
    keyPlaceholder: 'Private key (sign) or Public key (verify)',
  },
  {
    id: 'kcdsa',
    name: 'KCDSA',
    category: 'asymmetric',
    description: 'Korean national digital signature standard. DSA-family but hashes Message || w (commitment) instead of just Message. Note: Uses LSH-256 as a modernized substitute for the original HAS-160 pairing. Completes the Korean national suite.',
    defaultKey: '1234567890abcdef',
    defaultInput: '616263',
    securityStatus: 'secure',
    keyPlaceholder: 'Private key (sign) or Public key (verify)',
  },
  {
    id: 'goldwasser-micali',
    name: 'Goldwasser-Micali',
    category: 'asymmetric',
    description: 'First semantically-secure (IND-CPA) public-key scheme (1982). Based on Quadratic Residuosity. Deliberately probabilistic: encrypts bit-by-bit with massive ciphertext expansion to achieve semantic security.',
    defaultKey: 'mock',
    defaultInput: '01',
    securityStatus: 'secure',
    keyPlaceholder: 'Public key (encrypt) or Private key (decrypt)',
  },
  {
    id: 'ggh',
    name: 'GGH',
    category: 'asymmetric',
    description: 'Early lattice cryptosystem (1997). Uses good/bad basis pairs. Status: BROKEN unconditionally. Nguyen (1999) showed the specific error-vector distribution leaked structural information, making CVP trivial. Educational complement to secure NTRU/ML-KEM.',
    defaultKey: 'mock_keys',
    defaultInput: '050a',
    securityStatus: 'broken',
    keyPlaceholder: 'Public (bad basis) or Private (good basis)',
  },
  {
    id: 'bls',
    name: 'BLS',
    category: 'asymmetric',
    description: 'Pairing-based digital signatures (2001). Defining feature: Signature Aggregation. Multiple signatures can be combined into one compact signature verifiable against all original public keys. Used in Ethereum validator layer. (Toy pairing model for visualizer).',
    defaultKey: '1234567890abcdef',
    defaultInput: 'message',
    securityStatus: 'secure',
    keyPlaceholder: 'Private key (sign) or "pubkey,sig" (verify)',
  },
  {
    id: 'boneh-franklin-ibe',
    name: 'Boneh-Franklin IBE',
    category: 'asymmetric',
    description: 'Identity-Based Encryption (2001). The public key IS an arbitrary string (e.g., email). No PKI needed. A trusted Private Key Generator (PKG) derives private keys. Novel category: encrypt before recipient even exists.',
    defaultKey: '5,alice@example.com',
    defaultInput: '68656c6c6f',
    securityStatus: 'secure',
    keyPlaceholder: 'PKG_pub,identity (encrypt) or private_key (decrypt)',
  },
  {
    id: 'regev-lwe',
    name: 'Regev-LWE',
    category: 'asymmetric',
    description: 'Foundational LWE encryption (2005). The NOT-broken textbook predecessor to ML-KEM. Encodes bits by adding a large offset (floor(q/2)) hidden by small LWE noise. Explicitly distinguished from broken predecessors like GGH/SIDH.',
    defaultKey: 'mock_keys',
    defaultInput: '01',
    securityStatus: 'secure',
    keyPlaceholder: 'Public key (encrypt) or Private key (decrypt)',
  },
  {
    id: 'okamoto-uchiyama',
    name: 'Okamoto-Uchiyama',
    category: 'asymmetric',
    description: 'Probabilistic additively-homomorphic encryption (EUROCRYPT 1998). Modulus n=p²q (distinct from RSA/Paillier/GM). DEFINING ASYMMETRY: decryption uses only p, never q. Positioned between Goldwasser-Micali (probabilistic predecessor) and Paillier (homomorphic descendant).',
    defaultKey: 'mock',
    defaultInput: '05',
    securityStatus: 'secure',
    keyPlaceholder: 'Public key (encrypt) or Private key p (decrypt)',
  },
  {
    id: 'sqisign',
    name: 'SQIsign',
    category: 'asymmetric',
    description: 'Isogeny-based signature scheme (2020). NIST PQC candidate. Proves knowledge of an isogeny WITHOUT publishing torsion-point images, specifically avoiding the Castryck-Decru attack that broke SIDH. Shows isogeny cryptography survived where SIDH did not.',
    defaultKey: '1234',
    defaultInput: '68656c6c6f',
    securityStatus: 'secure',
    keyPlaceholder: 'Secret isogeny (sign) or Public curve EA (verify)',
  },
  {
    id: 'chor-rivest',
    name: 'Chor-Rivest',
    category: 'asymmetric',
    description: 'Knapsack cryptosystem disguised via discrete logarithms in the field extension GF(p^h) — genuinely more elaborate than Merkle-Hellman\'s modular-multiplication disguise. FIXED HAMMING WEIGHT constraint on messages. Status: BROKEN (Vaudenay 1998, targeting the GF(p^h) construction — distinct break from Merkle-Hellman\'s Shamir attack).',
    defaultKey: 'mock',
    defaultInput: 'e0',
    securityStatus: 'broken',
    keyPlaceholder: 'Public key (encrypt) or Private key (decrypt)',
  },
  {
    id: 'rainbow',
    name: 'Rainbow',
    category: 'asymmetric',
    description: 'Multivariate-quadratic signature scheme (Ding & Schmidt, 2005). NIST PQC ROUND 3 FINALIST, broken by Beullens (2022) in hours on a laptop — layered central map leaked exploitable algebraic structure. 4th major PQC family in this repo (alongside lattice/code-based/isogeny). Status: BROKEN unconditionally.',
    defaultKey: 'mock_private',
    defaultInput: '010203040506',
    securityStatus: 'broken',
    keyPlaceholder: 'Private key (sign) or Public key (verify)',
  },
  {
    id: 'mqv',
    name: 'MQV',
    category: 'asymmetric',
    description: 'Authenticated key agreement (Menezes-Qu-Vanstone, 1995). Bakes mutual authentication DIRECTLY INTO the key-agreement math by mixing long-term static keys with fresh ephemeral keys — no separate signature/certificate exchange needed. Distinct from unauthenticated DH/X25519/X448. Status: secure (with documented KCI nuance).',
    defaultKey: 'mock',
    defaultInput: 'mock',
    securityStatus: 'secure',
    keyPlaceholder: 'Static + Ephemeral key pairs',
  },
  {
    id: 'falcon',
    name: 'Falcon',
    category: 'asymmetric',
    description: 'NIST PQC standardized signature (FIPS 206). NTRU-lattice + Fast Fourier sampling over a four-polynomial trapdoor (f,g,F,G satisfying fG-gF=q). Produces notably COMPACT signatures vs. ML-DSA, at the cost of numerically delicate floating-point signing. Status: secure.',
    defaultKey: 'mock_private',
    defaultInput: '68656c6c6f',
    securityStatus: 'secure',
    keyPlaceholder: 'Private key (sign) or Message (verify)',
  },
  {
    id: 'niederreiter',
    name: 'Niederreiter',
    category: 'asymmetric',
    description: 'DUAL of Classic McEliece (1986). Syndrome-based code encryption: message encoded as exact-weight-t error vector, ciphertext is ONLY the (n-k)-bit syndrome — substantially SHORTER than McEliece\'s n-bit codeword. Proven equivalent in security. Toy parameters for visualizer.',
    defaultKey: 'mock',
    defaultInput: 'c0',
    securityStatus: 'secure',
    keyPlaceholder: 'Public key (encrypt) or Private key (decrypt)',
  },
];
